name: Build and deploy NestJS app to Azure Web App - foodexpress-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout your repo
      - uses: actions/checkout@v4

      # Set Node.js version to match your project
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      # Install dependencies and build NestJS backend
      - name: Install dependencies
        run: npm ci

      # Generate Prisma client
      - name: Generate Prisma client
        run: npx prisma generate

      # Build the application
      - name: Build application
        run: npm run build

      # Create deployment package
      - name: Create deployment package
        run: |
          mkdir deploy
          cp -r dist deploy/
          cp -r node_modules deploy/
          cp -r prisma deploy/
          cp package*.json deploy/
          cp -r .env.example deploy/ || true

      # Upload artifact to use in deploy job
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nestjs-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download built artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nestjs-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_XXXX }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_XXXX }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_XXXX }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodexpress-api'
          slot-name: 'Production'
          package: .
