name: Build and deploy NestJS app to Azure Web App - foodexpress-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout your repo
      - uses: actions/checkout@v4

      # Set Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install dependencies and build NestJS backend
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Upload artifact to use in deploy job
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nestjs-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download built artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nestjs-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_XXXX }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_XXXX }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_XXXX }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodexpress-api'
          slot-name: 'Production'
          package: .
